services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root                          # docker 명령어 실행 권한 위해 필요
    ports:
      - "8080:8080"                     # Jenkins 웹 UI
      - "50000:50000"                   # Jenkins 에이전트 연결용
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # 호스트 Docker 제어 권한
      - /usr/bin/docker:/usr/bin/docker              # 컨테이너 안에 docker 명령어 심기 (실제 경로로 수정)
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose
      - /home/ubuntu:/home/ubuntu

volumes:
  jenkins_home: