-- 추천 운동 기능 DDL (Oracle / MOTIVE 스키마)
-- 메인 홈 화면 "오늘의 추천 운동" 카드 기준으로 작성. 운영자가 등록해둔 운동 풀(POOL) 중
-- 일부를 화면에 무작위로 노출하는 에디토리얼 방식 — EXERCISES에 컬럼을 얹지 않고
-- 매핑 테이블로 분리했다(부위코드와 달리 "추천 여부"는 운동 자체의 속성이 아니라 운영 정책).
-- 시퀀스 채번 방식은 workout_record_ddl.sql과 동일 패턴.

CREATE SEQUENCE RECOMMENDED_EXERCISE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE RECOMMENDED_EXERCISE (
    RECOMMENDED_EXERCISE_ID NUMBER          NOT NULL,          -- RECOMMENDED_EXERCISE_SEQ 채번
    EXERCISE_ID             NUMBER          NOT NULL,
    SORT_NO                 NUMBER DEFAULT 0 NOT NULL,         -- 노출 순서(운영자 지정)
    SETS                    NUMBER DEFAULT 0 NOT NULL,         -- 권장 세트 수
    WEIGHT                  NUMBER(6,2) DEFAULT 0 NOT NULL,    -- 권장 중량(kg)
    REPS                    NUMBER DEFAULT 0 NOT NULL,         -- 권장 횟수(회)
    DURATION_MIN            NUMBER DEFAULT 0 NOT NULL,         -- 예상 소요 시간(분)
    REG_DT                  DATE DEFAULT SYSDATE NOT NULL,
    MOD_DT                  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RECOMMENDED_EXERCISE PRIMARY KEY (RECOMMENDED_EXERCISE_ID),
    CONSTRAINT FK_RECOMMENDED_EXERCISE_EXERCISE FOREIGN KEY (EXERCISE_ID) REFERENCES EXERCISES (EXERCISE_ID),
    CONSTRAINT UK_RECOMMENDED_EXERCISE_EXERCISE UNIQUE (EXERCISE_ID)  -- 같은 운동 중복 등록 방지
);

COMMENT ON TABLE RECOMMENDED_EXERCISE IS '추천 운동 풀(운영자 등록)';
COMMENT ON COLUMN RECOMMENDED_EXERCISE.RECOMMENDED_EXERCISE_ID IS '추천운동아이디';
COMMENT ON COLUMN RECOMMENDED_EXERCISE.EXERCISE_ID IS '운동아이디(FK)';
COMMENT ON COLUMN RECOMMENDED_EXERCISE.SORT_NO IS '노출 순서';
COMMENT ON COLUMN RECOMMENDED_EXERCISE.SETS IS '권장 세트 수';
COMMENT ON COLUMN RECOMMENDED_EXERCISE.WEIGHT IS '권장 중량(kg)';
COMMENT ON COLUMN RECOMMENDED_EXERCISE.REPS IS '권장 횟수(회)';
COMMENT ON COLUMN RECOMMENDED_EXERCISE.DURATION_MIN IS '예상 소요 시간(분)';
COMMENT ON COLUMN RECOMMENDED_EXERCISE.REG_DT IS '등록일시';
COMMENT ON COLUMN RECOMMENDED_EXERCISE.MOD_DT IS '수정일시';

-- 관리 화면 나오기 전까지 임시 시드 예시 (EXERCISE_ID는 실제 값으로 교체해서 사용)
-- INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
-- VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 1, 10, 4, 35, 10, 8);
