-- 추천 운동 풀 추가 시드 — 하체/어깨/삼두/이두/코어
-- (등,이두) / (가슴,삼두) / (어깨,코어) / (하체) 조합용

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 12, 90, 4, 50, 8, 10);   -- 스쿼트 (하체)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 13, 100, 3, 80, 12, 8);  -- 레그프레스 (하체)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 16, 110, 3, 20, 12, 7);  -- 런지 (하체)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 17, 120, 4, 30, 10, 8);  -- 밀리터리 프레스 (어깨)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 18, 130, 3, 8, 15, 6);   -- 사이드 레터럴레이즈 (어깨)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 29, 140, 3, 16, 10, 7);  -- 덤벨 숄더프레스 (어깨)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 20, 150, 3, 20, 12, 6);  -- 트라이셉스 익스텐션 (삼두)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 21, 160, 3, 25, 12, 6);  -- 케이블 푸시다운 (삼두)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 23, 170, 4, 25, 10, 7);  -- 바벨 컬 (이두)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 24, 180, 3, 12, 10, 6);  -- 덤벨 컬 (이두)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 25, 190, 3, 14, 10, 6);  -- 해머 컬 (이두)

-- 플랭크는 세트/무게/횟수 모델과 안 맞는 시간제 운동이라 REPS를 "초"로 임시 사용(근사치)
INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 26, 200, 3, 0, 30, 4);   -- 플랭크 (코어)

INSERT INTO RECOMMENDED_EXERCISE (RECOMMENDED_EXERCISE_ID, EXERCISE_ID, SORT_NO, SETS, WEIGHT, REPS, DURATION_MIN)
VALUES (RECOMMENDED_EXERCISE_SEQ.NEXTVAL, 27, 210, 3, 0, 20, 5);   -- 크런치 (코어)

COMMIT;
